
build:
  version: 1.0

training-service:
  message: "Welcome to TRAINING Microservice DEFAULT Profile"
  contactDetails:
    name: "Samyak"
    email: "samyak@gmail.com"
  onCallSupport:
    - (000)310-8714
    - (000)487-3102
